version: "3"
services:
  web:
    image: node:10.16.3
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/web
    working_dir: /web
    user: ${CURRENT_UID}
    command:
      - npm
      - run
      - dev